# Generated by Django 6.0.6 on 2026-07-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apitoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIToken',
        ),
    ]
