# Generated by Django 6.0.6 on 2026-08-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_pending', 'Post Pending'), ('post_approved', 'Post Approved'), ('post_rejected', 'Post Rejected')], default='post_pending', max_length=100),
        ),
    ]
